"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[package]
disabled = false

[character]
success_symbol = '[ ](bold #cba6f7)[ ](bold #f2cdcd)[ ](bold #b4befe)[ ](bold #a6e3a1)'
error_symbol = '[ ](bold #cba6f7)[ ](bold #f2cdcd)[ ](bold #b4befe)[ ](bold #f38ba8)'
vimcmd_symbol = '[ NORMAL](bold #fab387)'
vimcmd_visual_symbol = '[ VISUAL](bold #89dceb)'

[git_branch]
symbol = ' '

[git_status]
modified = ''
untracked = ''
staged = ''

[nodejs]
disabled = true


#[custom_test_dir_prompt]
#when = '"test" in directory'
#format = "%F{green}[%n@%m %1~] %% %f"



